version: "2"

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - bodyclose
    - misspell
    - revive
    - unconvert
    - gocritic

formatters:
  enable:
    - gofmt
